version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/workspace/database/database.sqlite
    command: >
      sh -c "
        if [ ! -f database/database.sqlite ]; then
          touch database/database.sqlite;
        fi &&
        php artisan migrate --force &&
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      " 