version: '3.8'

services:
  app:
    build: .
    expose:
      - "9000"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./public:/var/www/html/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: >
      sh -c "
        if [ ! -f database/database.sqlite ]; then
          touch database/database.sqlite;
        fi &&
        php artisan migrate --force &&
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
      "

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public 