services:
  - type: web
    name: laravel-pendaftaran
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync 